# Generated by Django 4.1.13 on 2026-04-09 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='actus/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentIntranet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='intranet_docs/')),
                ('categorie', models.CharField(choices=[('FORMATION', 'Manuel & Formation'), ('PLAN', 'Plan de Patrouille & Cartes'), ('CR', 'Compte-Rendu de Réunion'), ('AUTRE', 'Autre Document')], default='AUTRE', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('VEHICULE', 'Véhicule'), ('RADIO', 'Radio'), ('OUTIL', 'Outil / Pompe')], max_length=20)),
                ('en_service', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Prénom et Nom', max_length=100)),
                ('role', models.CharField(help_text="Ex: Président, Chef d'équipe...", max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipe/')),
                ('ordre', models.IntegerField(default=0, help_text='Mettre 1 pour le président, 2 pour le vice-président, etc.')),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGalerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex: Formation avec le SDIS', max_length=100)),
                ('image', models.ImageField(upload_to='galerie/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RisqueIncendie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('JAUNE', 'Modéré (Jaune)'), ('ORANGE', 'Sévère (Orange)'), ('ROUGE', 'Très Sévère (Rouge)'), ('NOIR', 'Extrême (Noir)')], default='ORANGE', max_length=10)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patrouille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_patrouille', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_patrouille', models.CharField(choices=[('MOBILE', 'Patrouille Mobile (4x4)'), ('VIGIE', 'Point de Vigie')], default='MOBILE', max_length=20)),
                ('rapport', models.TextField(blank=True, help_text='RAS ou incidents à signaler', null=True)),
                ('chef_de_bord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrouilles_dirigees', to=settings.AUTH_USER_MODEL)),
                ('coequipier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrouilles_assistees', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(blank=True, limit_choices_to={'categorie': 'VEHICULE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.materiel')),
            ],
            options={
                'ordering': ['date_patrouille', 'heure_debut'],
            },
        ),
    ]
