# Generated by Django 4.1.13 on 2026-04-09 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrouille',
            name='est_terminee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patrouille',
            name='km_debut',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patrouille',
            name='km_fin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patrouille',
            name='meteo',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Temps calme / Dégagé'), ('VENT', 'Mistral / Vent fort'), ('CANICULE', 'Forte chaleur'), ('ORAGE', 'Risque Orageux')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex: DEPART DE FEU - MASSIF NORD', max_length=100)),
                ('message', models.TextField(help_text='Instructions pour les bénévoles')),
                ('est_active', models.BooleanField(default=True)),
                ('date_lancement', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
