# Generated by Django 4.1.13 on 2026-04-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patrouille_est_terminee_patrouille_km_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrouille',
            name='chk_carburant',
            field=models.BooleanField(default=False, verbose_name='Plein de carburant'),
        ),
        migrations.AddField(
            model_name='patrouille',
            name='chk_eau',
            field=models.BooleanField(default=False, verbose_name="Niveau d'eau / LDR"),
        ),
        migrations.AddField(
            model_name='patrouille',
            name='chk_huile',
            field=models.BooleanField(default=False, verbose_name="Niveau d'huile"),
        ),
        migrations.AddField(
            model_name='patrouille',
            name='chk_pneus',
            field=models.BooleanField(default=False, verbose_name='État des pneus'),
        ),
        migrations.AddField(
            model_name='patrouille',
            name='chk_pompe',
            field=models.BooleanField(default=False, verbose_name='Test motopompe / Eau cuve'),
        ),
        migrations.AddField(
            model_name='patrouille',
            name='chk_radio',
            field=models.BooleanField(default=False, verbose_name='Essai Radio VHF'),
        ),
        migrations.AddField(
            model_name='patrouille',
            name='mission_type',
            field=models.CharField(choices=[('CCFF', 'Mission CCFF (Communale)'), ('RCSC', 'Mission RCSC (Réserve Civile)')], default='CCFF', max_length=10),
        ),
        migrations.AddField(
            model_name='patrouille',
            name='signature_chef',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patrouille',
            name='signature_coequipier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patrouille',
            name='rapport',
            field=models.TextField(blank=True, help_text='Main courante / incidents', null=True),
        ),
    ]
