# Generated by Django 4.1.13 on 2026-04-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_messagecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Prénom et Nom', max_length=100)),
                ('role', models.CharField(help_text="Ex: Président, Chef d'équipe...", max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipe/')),
                ('ordre', models.IntegerField(default=0, help_text='Mettre 1 pour le président, 2 pour le vice-président, etc.')),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PhotoGalerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex: Formation avec le SDIS', max_length=100)),
                ('image', models.ImageField(upload_to='galerie/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
