# Generated by Django 4.1.13 on 2026-04-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_patrouille_chk_carburant_patrouille_chk_eau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrouille',
            name='rapport_pdf',
            field=models.FileField(blank=True, null=True, upload_to='rapports_pdf/'),
        ),
    ]
