# Generated by Django 4.1.13 on 2026-04-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_membreequipe_photogalerie'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentIntranet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='intranet_docs/')),
                ('categorie', models.CharField(choices=[('FORMATION', 'Manuel & Formation'), ('PLAN', 'Plan de Patrouille & Cartes'), ('CR', 'Compte-Rendu de Réunion'), ('AUTRE', 'Autre Document')], default='AUTRE', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
