# Generated by Django 4.1.13 on 2026-04-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patrouille_rapport_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonneNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Adresse email de l'habitant", max_length=254, unique=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True, help_text='Abonné aux alertes et newsletters')),
            ],
            options={
                'verbose_name': 'Abonné Newsletter',
                'verbose_name_plural': 'Abonnés Newsletter',
            },
        ),
    ]
