# Generated by Django 4.1.13 on 2026-04-09 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_documentintranet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrouille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_patrouille', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_patrouille', models.CharField(choices=[('MOBILE', 'Patrouille Mobile (4x4)'), ('VIGIE', 'Point de Vigie')], default='MOBILE', max_length=20)),
                ('rapport', models.TextField(blank=True, help_text='RAS ou incidents à signaler', null=True)),
                ('benevoles', models.ManyToManyField(related_name='patrouilles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
