# Generated by Django 4.1.13 on 2026-04-09 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_abonnenewsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Décrivez le problème (ex: Pneu crevé, radio grésille...)')),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('est_resolu', models.BooleanField(default=False)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='core.materiel')),
                ('signale_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement Matériel',
                'verbose_name_plural': 'Signalements Matériel',
                'ordering': ['-date_signalement'],
            },
        ),
    ]
