# Generated by Django 4.1.13 on 2026-04-09 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_signalementmateriel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierGalerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du dossier (ex: Formation SDIS 2024)', max_length=100, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dossier Galerie',
                'verbose_name_plural': 'Dossiers Galerie',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AlterField(
            model_name='photogalerie',
            name='titre',
            field=models.CharField(help_text='Légende de la photo', max_length=100),
        ),
        migrations.AddField(
            model_name='photogalerie',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='core.dossiergalerie'),
        ),
    ]
