# Generated by Django 4.1.13 on 2026-04-09 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_dossiergalerie_alter_photogalerie_titre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Veste F1, Pantalon, Rangers...', max_length=100)),
                ('categorie', models.CharField(choices=[('VETEMENT', 'Vêtement (Veste, Pantalon, Polo)'), ('CHAUSSURE', 'Chaussures / Rangers'), ('EPI', 'Équipement (Casque, Gants, Lampe)')], default='VETEMENT', max_length=20)),
                ('prix_indicatif', models.DecimalField(blank=True, decimal_places=2, help_text='Pour estimer la valeur du vestiaire', max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Article EPI',
                'verbose_name_plural': 'Articles EPI',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Dotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.CharField(help_text='Ex: M, XL, 42, 44...', max_length=20)),
                ('date_remise', models.DateField(auto_now_add=True)),
                ('etat_actuel', models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon état'), ('USE', 'Usé / À remplacer')], default='NEUF', max_length=10)),
                ('est_rendu', models.BooleanField(default=False, help_text='Cocher quand le bénévole rend le matériel')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.articleepi')),
                ('benevole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dotation Bénévole',
                'verbose_name_plural': 'Dotations Bénévoles',
                'ordering': ['benevole__first_name', '-date_remise'],
            },
        ),
    ]
