# Generated by Django 4.1.13 on 2026-04-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_articleepi_dotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='est_traite',
            field=models.BooleanField(default=False, help_text='Cocher quand la candidature a été traitée'),
        ),
        migrations.AddField(
            model_name='messagecontact',
            name='est_traite',
            field=models.BooleanField(default=False, help_text='Cocher quand une réponse a été apportée'),
        ),
    ]
