# Generated by Django 4.1.13 on 2026-04-09 21:37

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_candidature_est_traite_messagecontact_est_traite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentintranet',
            name='fichier',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='intranet_docs/'),
        ),
        migrations.AlterField(
            model_name='patrouille',
            name='rapport_pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='rapports_pdf/'),
        ),
    ]
