# Generated by Django 4.1.13 on 2026-04-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_documentintranet_fichier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrouille',
            name='rapport_pdf',
        ),
    ]
